services:
  mongo:
    image: mongo:8.0.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo_data:/data/db
      - ./seeders/seed-mongo.js:/docker-entrypoint-initdb.d/seed-mongo.js
    networks:
      - db_network
    restart: unless-stopped

  neo4j:
    image: neo4j:5.26-community
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./data/neo4j_data:/data
      - ./seeders/seed-neo4j.cypher:/var/lib/neo4j/import/seed-neo4j.cypher
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - db_network

  node-app:
    build:
      context: ./api
      # TODO: change to prod.Dockerfile when in production
      dockerfile: docker/prod.Dockerfile
    container_name: app-node
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - mongo
      - neo4j
    networks:
      - db_network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - node-app
      - mongo
      - neo4j
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "8080:8080"
    networks:
      - db_network

volumes:
  mongo_data:
  neo4j_data:

networks:
  db_network:
    driver: bridge
